name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  path: ^1.8.0
  backfit:
    path: ../backfit

dev_dependencies:
  build_runner: null
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  backfit_generator:
    path: ../backfit_generator
