targets:
  $default:
    builders:
      backfit_generator|backfit:
        enabled: true

builders:
  backfit_generator:
    import: "package:backfit_generator/backfit_generator.dart"
    builder_factories: ["backfitGeneratorFactory"]
    build_extensions: {".dart": [".backfit.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]