name: backfit_generator
description: Source code generator for Backfit package.
version: 0.0.1
author: null
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.1.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  path: ^1.8.0
  source_gen: ^1.1.0
  backfit:
    path: ../backfit

dev_dependencies:
  build_runner:
