name: backfit_generator
description: Source code generator for Backfit package.
version: 0.0.2
repository: https://github.com/astralstriker/backfit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.1.0
  backfit: ^0.0.2
  build: ^2.1.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.1.0

dev_dependencies:
  build_runner:
